
source "https://rubygems.org"
gem "jekyll", "~>4.4"
gem "jekyll-feed", "~>0.17"
gem "jekyll-sitemap", "~>1.4"
gem "jekyll-seo-tag", "~>2.8"
gem "jekyll-paginate", "~>1.1.0"
gem "jekyll-last-modified-at", "~>1.2"
gem "jekyll-archives", "~>2.2"
gem "jekyll-toc", "~>0.19"
gem "jekyll-minifier", "~>0.2"
gem "jekyll-postcss"
